version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached
    ports:
      - 80:80

    command:
      - /bin/bash
      - -c
      - |
        [ -d vendor/bin ] || composer install
        [ -f .env ] || { cp .env.example .env; php artisan key:generate --ansi; }
        apache2-foreground

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    ports:
      - 8112:3306
    volumes:
      - db-volume:/var/lib/mysql:cached

volumes:
  db-volume:
